apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
        - name: app-flask-deployment
          image: altabored/app-flask:$(Build.BuildId)
          ports:
            - containerPort: 5000