apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_flask_deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app_flask
  template:
    metadata:
      labels:
        app: app_flask
    spec:
      containers:
        - name: app_flask_container
          image: app_flask:1.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app_flask
    k8s-app: app_flask
  name: app_flask
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  type: LoadBalancer
  selector:
    app: app_flask
