apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
        - name: app-flask-container
          image: app-flask:$(Build.BuildId)
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-flask
    k8s-app: app-flask
  name: app-flask
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  type: LoadBalancer
  selector:
    app: app-flask
