apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
      - name: app-flask
        image: altabored/app-flask:${BUILD_NUMBER}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-flask-service
spec:
  type: LoadBalancer
  selector:
    app: app-flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
